[workspace]
members = [
    "backyard",
    "collections",
    "control_flow",
    "data_types",
    "enums",
    "error_handling",
    "functions",
    "generics",
    "guessing_game",
    "hello",
    "iters_and_closures",
    "lifetimes",
    "minigrep",
    "my_crate",
    "ownership",
    "references_borrowing",
    "restaurant",
    "slice_type",
    "smart_pointers",
    "structs",
    "tests",
    "traits",
    "variables",
]
resolver="2"

[workspace.package]
version="0.1.0"
authors=["Andre Arcaina"]
